Train Epoch: 1 [0/2608 (0%)]	Loss: 0.006818
Train Epoch: 1 [400/2608 (15%)]	Loss: 0.001671
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    optimizer=optimizer, epoch=epoch)                ###logger added
  File "C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\train.py", line 9, in train
    for batch_idx, (data, target) in enumerate(train_loader): # <-- now it is a distributed dataset
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\utils\data\dataloader.py", line 345, in __next__
    data = self._next_data()
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\utils\data\dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\torch\utils\data\_utils\fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\dataloader.py", line 51, in __getitem__
    image = PIL.ImageOps.grayscale(image)
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\PIL\ImageOps.py", line 476, in grayscale
    return image.convert("L")
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\PIL\Image.py", line 893, in convert
    self.load()
  File "C:\Users\kevin\anaconda3\envs\fl\lib\site-packages\PIL\ImageFile.py", line 265, in load
    n, err_code = decoder.decode(b)
KeyboardInterrupt
