2021-01-12 20:16:17,348 INFO    MainThread:18368 [wandb_setup.py:_flush():70] setting env: {}
2021-01-12 20:16:17,350 INFO    MainThread:18368 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-01-12 20:16:17,350 INFO    MainThread:18368 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-12 20:16:17,350 INFO    MainThread:18368 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210112_201617-1hzjhvvg\logs\debug.log
2021-01-12 20:16:17,350 INFO    MainThread:18368 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210112_201617-1hzjhvvg\logs\debug-internal.log
2021-01-12 20:16:20,047 INFO    MainThread:18368 [wandb_run.py:_console_start():1237] atexit reg
2021-01-12 20:16:20,049 INFO    MainThread:18368 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2021-01-12 20:16:20,050 INFO    MainThread:18368 [wandb_run.py:_redirect():1135] Wrapping output streams.
2021-01-12 20:16:20,050 INFO    MainThread:18368 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-12 20:24:02,372 INFO    MainThread:18368 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 255
2021-01-12 20:24:02,373 INFO    MainThread:18368 [wandb_run.py:_restore():1179] restore
2021-01-12 20:24:02,382 INFO    MainThread:18368 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "ab076262521141558b63a22b2609191c"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 880
      total_bytes: 880
    }
  }
}

2021-01-12 20:24:04,392 INFO    MainThread:18368 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "e2c34e24be4f4cc2a4668ac8bb492cc9"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 10556
      total_bytes: 10556
    }
  }
}

2021-01-12 20:24:06,394 INFO    MainThread:18368 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "4b7a789d44314d1eb92167dd04697f26"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 10556
      total_bytes: 10556
    }
  }
}

2021-01-12 20:24:07,519 INFO    MainThread:18368 [wandb_run.py:_show_summary():1469] rendering summary
2021-01-12 20:24:07,523 INFO    MainThread:18368 [wandb_run.py:_show_history():1507] rendering history
2021-01-12 20:24:07,530 INFO    MainThread:18368 [wandb_run.py:_show_files():1536] logging synced files
2021-01-12 20:24:07,538 INFO    MainThread:18368 [internal.py:handle_exit():138] Internal process exited
