2021-01-11 16:58:35,163 INFO    MainThread:3360 [wandb_setup.py:_flush():70] setting env: {}
2021-01-11 16:58:35,163 INFO    MainThread:3360 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-01-11 16:58:35,163 INFO    MainThread:3360 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-11 16:58:35,164 INFO    MainThread:3360 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210111_165835-xhx3lcmt\logs\debug.log
2021-01-11 16:58:35,164 INFO    MainThread:3360 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210111_165835-xhx3lcmt\logs\debug-internal.log
2021-01-11 16:58:37,398 INFO    MainThread:3360 [wandb_run.py:_console_start():1237] atexit reg
2021-01-11 16:58:37,399 INFO    MainThread:3360 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2021-01-11 16:58:37,400 INFO    MainThread:3360 [wandb_run.py:_redirect():1135] Wrapping output streams.
2021-01-11 16:58:37,400 INFO    MainThread:3360 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-11 17:49:48,118 INFO    MainThread:3360 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-11 17:49:48,118 INFO    MainThread:3360 [wandb_run.py:_restore():1179] restore
2021-01-11 17:49:48,121 INFO    MainThread:3360 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "6352593e691e40b89b046d6423368243"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 983
      total_bytes: 983
    }
  }
}

2021-01-11 17:49:50,126 INFO    MainThread:3360 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "3fdb6b48279648369f42c146e44dbda7"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 7760
      total_bytes: 7760
    }
  }
}

2021-01-11 17:49:52,130 INFO    MainThread:3360 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "83b9cfa43e1c4fcf803032c54f7288ee"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 7760
      total_bytes: 7760
    }
  }
}

2021-01-11 17:49:53,422 INFO    MainThread:3360 [wandb_run.py:_show_summary():1469] rendering summary
2021-01-11 17:49:53,425 INFO    MainThread:3360 [wandb_run.py:_show_history():1507] rendering history
2021-01-11 17:49:53,508 INFO    MainThread:3360 [wandb_run.py:_show_files():1536] logging synced files
2021-01-11 17:49:53,529 INFO    MainThread:3360 [internal.py:handle_exit():138] Internal process exited
