2021-01-12 19:34:43,624 INFO    MainThread:16404 [wandb_setup.py:_flush():70] setting env: {}
2021-01-12 19:34:43,624 INFO    MainThread:16404 [wandb_setup.py:_flush():70] multiprocessing start_methods=spawn
2021-01-12 19:34:43,624 INFO    MainThread:16404 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-12 19:34:43,624 INFO    MainThread:16404 [wandb_init.py:_log_setup():303] Logging user logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210112_193443-tc4lzyuz\logs\debug.log
2021-01-12 19:34:43,624 INFO    MainThread:16404 [wandb_init.py:_log_setup():304] Logging internal logs to C:\Users\kevin\OneDrive\Documents\8th sem\Federated_Pneumonia\src\client\wandb\run-20210112_193443-tc4lzyuz\logs\debug-internal.log
2021-01-12 19:34:47,464 INFO    MainThread:16404 [wandb_run.py:_console_start():1237] atexit reg
2021-01-12 19:34:47,464 INFO    MainThread:16404 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2021-01-12 19:34:47,464 INFO    MainThread:16404 [wandb_run.py:_redirect():1135] Wrapping output streams.
2021-01-12 19:34:47,464 INFO    MainThread:16404 [wandb_run.py:_redirect():1151] Redirects installed.
2021-01-12 19:49:16,637 INFO    MainThread:16404 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2021-01-12 19:49:16,652 INFO    MainThread:16404 [wandb_run.py:_restore():1179] restore
2021-01-12 19:49:16,652 INFO    MainThread:16404 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "f2091f82259c4927b559a032b6aa8067"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 1018
      total_bytes: 1018
    }
  }
}

2021-01-12 19:49:18,678 INFO    MainThread:16404 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "4ece688ffe0a48129168eb1ecb383738"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 6525
      total_bytes: 6525
    }
  }
}

2021-01-12 19:49:20,683 INFO    MainThread:16404 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "606f58eab73d4012a968b20493baef57"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 5
    }
    pusher_stats {
      uploaded_bytes: 6525
      total_bytes: 6525
    }
  }
}

2021-01-12 19:49:22,180 INFO    MainThread:16404 [wandb_run.py:_show_summary():1469] rendering summary
2021-01-12 19:49:22,180 INFO    MainThread:16404 [wandb_run.py:_show_history():1507] rendering history
2021-01-12 19:49:22,212 INFO    MainThread:16404 [wandb_run.py:_show_files():1536] logging synced files
2021-01-12 19:49:22,212 INFO    MainThread:16404 [internal.py:handle_exit():138] Internal process exited
