2020-12-27 20:48:33,489 INFO    MainThread:10355 [wandb_setup.py:_flush():70] setting env: {}
2020-12-27 20:48:33,489 INFO    MainThread:10355 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-27 20:48:33,489 INFO    MainThread:10355 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-27 20:48:33,490 INFO    MainThread:10355 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-27 20:48:33,490 INFO    MainThread:10355 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f6e43f2b090>
2020-12-27 20:48:33,491 INFO    MainThread:10355 [wandb_init.py:_log_setup():303] Logging user logs to /home/nikamanth/Documents/fyp/notebooks/wandb/run-20201227_204833-32de24jp/logs/debug.log
2020-12-27 20:48:33,491 INFO    MainThread:10355 [wandb_init.py:_log_setup():304] Logging internal logs to /home/nikamanth/Documents/fyp/notebooks/wandb/run-20201227_204833-32de24jp/logs/debug-internal.log
2020-12-27 20:48:35,226 ERROR   MainThread:10355 [wandb_init.py:init():601] error
Traceback (most recent call last):
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 575, in init
    run = wi.init()
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 411, in init
    ret = backend.interface.communicate_run(run, timeout=30)
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 541, in communicate_run
    run = self._make_run(run_obj)
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 182, in _make_run
    run._make_proto_run(proto_run)
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 315, in _make_proto_run
    run.job_type = self._job_type
TypeError: VGG(
  (avgpool): AdaptiveAvgPool2d(output_size=(7, 7))
  (classifier): Sequential(
    (0): Linear( has type VGG, but expected one of: bytes, unicode
2020-12-27 20:48:46,087 INFO    MainThread:10355 [wandb_settings.py:_apply_source_login():607] setting login settings: {}
2020-12-27 20:48:46,104 INFO    MainThread:10355 [wandb_setup.py:_flush():70] setting env: {}
2020-12-27 20:48:46,104 INFO    MainThread:10355 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-27 20:48:46,104 INFO    MainThread:10355 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-27 20:48:46,104 INFO    MainThread:10355 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-27 20:48:46,104 INFO    MainThread:10355 [wandb_setup.py:_flush():70] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f6e43f2b090>
2020-12-27 20:48:46,105 INFO    MainThread:10355 [wandb_init.py:_log_setup():303] Logging user logs to /home/nikamanth/Documents/fyp/notebooks/wandb/run-20201227_204846-b4pgjidz/logs/debug.log
2020-12-27 20:48:46,105 INFO    MainThread:10355 [wandb_init.py:_log_setup():304] Logging internal logs to /home/nikamanth/Documents/fyp/notebooks/wandb/run-20201227_204846-b4pgjidz/logs/debug-internal.log
2020-12-27 20:48:47,614 INFO    MainThread:10355 [wandb_run.py:_console_start():1237] atexit reg
2020-12-27 20:48:47,615 INFO    MainThread:10355 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.WRAP
2020-12-27 20:48:47,616 INFO    MainThread:10355 [wandb_run.py:_redirect():1135] Wrapping output streams.
2020-12-27 20:48:47,616 INFO    MainThread:10355 [wandb_run.py:_redirect():1151] Redirects installed.
2020-12-27 21:35:44,174 INFO    MainThread:10355 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 0
2020-12-27 21:35:44,176 INFO    MainThread:10355 [wandb_run.py:_restore():1179] restore
2020-12-27 21:35:44,184 INFO    MainThread:10355 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "d3c12d93acb84435b8e5b09b22e896e6"
response {
  poll_exit_response {
    file_counts {
      wandb_count: 1
    }
    pusher_stats {
      uploaded_bytes: 878
      total_bytes: 878
    }
  }
}

2020-12-27 21:35:46,188 INFO    MainThread:10355 [wandb_run.py:_wait_for_finish():1324] got exit ret: uuid: "8bb267f4cdfd422f8ab441ce07ec2c3e"
response {
  poll_exit_response {
    done: true
    exit_result {
    }
    file_counts {
      wandb_count: 4
    }
    pusher_stats {
      uploaded_bytes: 3602
      total_bytes: 3602
    }
  }
}

2020-12-27 21:35:47,283 INFO    MainThread:10355 [wandb_run.py:_show_files():1536] logging synced files
