Train Epoch: 1 [0/2608 (0%)]	Loss: 0.679847
Train Epoch: 1 [800/2608 (31%)]	Loss: 0.494921
Train Epoch: 1 [1600/2608 (61%)]	Loss: 0.333535
Train Epoch: 1 [2400/2608 (92%)]	Loss: 0.517593
Average loss : 0.506474144756794
model sent successfully!
Train Epoch: 1 [0/2608 (0%)]	Loss: 0.306269
Train Epoch: 1 [800/2608 (31%)]	Loss: 0.288702
Train Epoch: 1 [1600/2608 (61%)]	Loss: 0.268474
Train Epoch: 1 [2400/2608 (92%)]	Loss: 0.085323
Average loss : 0.23719180561602116
model sent successfully!
Train Epoch: 1 [0/2608 (0%)]	Loss: 0.101585
Train Epoch: 1 [800/2608 (31%)]	Loss: 0.228668
Train Epoch: 1 [1600/2608 (61%)]	Loss: 0.225577
Train Epoch: 1 [2400/2608 (92%)]	Loss: 0.104800
Average loss : 0.1651573609560728
model sent successfully!
Train Epoch: 1 [0/2608 (0%)]	Loss: 0.168530
Train Epoch: 1 [800/2608 (31%)]	Loss: 0.048827
Traceback (most recent call last):
  File "run.py", line 46, in <module>
    optimizer=optimizer, epoch=epoch)                ###logger added
  File "/home/nikamanth/Documents/fyp/src/client/train.py", line 9, in train
    for batch_idx, (data, target) in enumerate(train_loader): # <-- now it is a distributed dataset
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/nikamanth/Documents/fyp/src/client/dataloader.py", line 51, in __getitem__
    image = PIL.ImageOps.grayscale(image)
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/PIL/ImageOps.py", line 476, in grayscale
    return image.convert("L")
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/PIL/Image.py", line 893, in convert
    self.load()
  File "/home/nikamanth/anaconda3/envs/torch/lib/python3.7/site-packages/PIL/ImageFile.py", line 265, in load
    n, err_code = decoder.decode(b)
KeyboardInterrupt
