 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
wandb: Currently logged in as: nikamanth (use `wandb login --relogin` to force relogin)
wandb: wandb version 0.10.14 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.10.12
wandb: Syncing run genial-plasma-23
wandb: ‚≠êÔ∏è View project at https://wandb.ai/nikamanth/fed-learning
wandb: üöÄ View run at https://wandb.ai/nikamanth/fed-learning/runs/4rl9qx7o
wandb: Run data is saved locally in /home/nikamanth/Documents/fyp/src/aggregator/wandb/run-20210116_120013-4rl9qx7o
wandb: Run `wandb offline` to turn off syncing.
 * Debugger is active!
 * Debugger PIN: 298-623-058
Connecting Nodes:127.0.0.1 - - [16/Jan/2021 12:00:31] "[37mPOST /getConnection HTTP/1.1[0m" 200 -

node_0
127.0.0.1 - - [16/Jan/2021 12:00:32] "[37mPOST /checkphase HTTP/1.1[0m" 200 -
model initialized
127.0.0.1 - - [16/Jan/2021 12:00:32] "[37mPOST /getmodel HTTP/1.1[0m" 200 -
 * Detected change in '/home/nikamanth/Documents/fyp/src/aggregator/config.py', reloading
 * Detected change in '/home/nikamanth/Documents/fyp/src/aggregator/config.py', reloading
wandb: Waiting for W&B process to finish, PID 7961
wandb: Program failed with code 3.  Press ctrl-c to abort syncing.
wandb: - 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb: \ 0.00MB of 0.00MB uploaded (0.00MB deduped)wandb:                                                                                
wandb: ERROR Control-C detected -- Run data was not synced
